version: '3.8'

services:
  backend:
    image: spotmusic-backend:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/spotmusic
    depends_on:
      - db

  frontend:
    image: spotmusic-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spotmusic